= Hawkular Alerting Demo

This repository contains resources to prepare a standalone demo for Hawkular Alerting.

NOTE: This demo has been tested on Linux platforms. Bash scripts can be easily translated into other platforms.

== Step 0: Prepare Hawkular Alerting

Build a Hawkular Alerting standalone distribution

[source,shell,subs="+attributes"]
----
    git clone https://github.com/hawkular/hawkular-alerts.git
    cd hawkular-alerts
    mvn clean install
----

Start the standalone server

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/
    bin/standalone.sh
----

[TIP]
.Test Email server
==================
By default, Hawkular Alerting will send email notifications using a SMTP server on localhost:25, for demo purposes
 a test smtp server can be used to validate the reception of the emails. +
  +
Hawkular Alerting has been tested using
  https://nilhcem.github.io/FakeSMTP/[FakeSMTP]. +
  +
A GUI SMTP server can be set up with these steps:
[source,shell,subs="+attributes"]
----
    git clone https://github.com/Nilhcem/FakeSMTP
    cd FakeSMTP
    mvn clean install -DskipTests
    cd target
    sudo java -jar fakeSMTP-*.jar
----
==================

== Step I: Install and start a Wildfly Server

In a new bash session:
 +
[source,shell,subs="+attributes"]
----    
    ./01_install.sh
----
 +

It downloads and installs on current folder a Wildfly Server. +
This Wildfly Server will be used to send data and events into Hawkular Alerting.

Then +

[source,shell,subs="+attributes"]
----    
    ./02_start-wildfly.sh
----

It starts a Wildfly Server with a port-offset=150.

== Step II: Import triggers definitions

[source,shell,subs="+attributes"]
----    
    ./03_import-definitions.sh
----

== Step III: Start a process agent

In a new bash session:
 +
[source,shell,subs="+attributes"]
----    
    ./04_agent-process.sh
----

=== Step III.a: Stop the Wildfly Server

Try to stop the Wildfly Server started on Step I with a CTRL+C. +
Check that in two seconds Hawkular Alerting should receive an Alert like:

[source,shell,subs="+attributes"]
----  
21:16:43,555 INFO  [org.hawkular.alerts.actions.api] (standalone-action-0) HAWKALERT240001: Plugin [email] has received an action message: [StandaloneActionMessage[action=Action[eventId='wildfly-availability-1478549803040-a3de9345-8a97-4cd9-a18f-3e32b1791f70', ctime=1478549803042, event=Alert{severity=CRITICAL, status=OPEN, notes=[], lifecycle=[LifeCycle{user='system', status=OPEN, stime=1478549803040}], resolvedEvalSets=null}, result='WAITING']]]
----

If an smtp email server is configured you should received a proper Alert [open] email.

=== Step III.b: Re-start the Wildfly Server

Re-start the server with the script

[source,shell,subs="+attributes"]
----    
    ./02_start-wildfly.sh
----

Check that Hawkular Alerting should automatically resolve the open Alert.

[source,shell,subs="+attributes"]
----
21:16:59,549 INFO  [org.hawkular.alerts.actions.api] (standalone-action-1) HAWKALERT240001: Plugin [email] has received an action message: [StandaloneActionMessage[action=Action[eventId='wildfly-availability-1478549803040-a3de9345-8a97-4cd9-a18f-3e32b1791f70', ctime=1478549819082, event=Alert{severity=CRITICAL, status=RESOLVED, notes=[Note{user='AutoResolve', ctime=1478549819066, text='Trigger AutoResolve=True'}], lifecycle=[LifeCycle{user='system', status=OPEN, stime=1478549803040}, LifeCycle{user='AutoResolve', status=RESOLVED, stime=1478549819066}], resolvedEvalSets=[[AvailabilityConditionEval [condition=AvailabilityCondition [triggerId='wildfly-availability', triggerMode=AUTORESOLVE, dataId='demo-avail', operator='UP'], value=UP, match=true, evalTimestamp=1478549819038, dataTimestamp=1478549817727]]]}, result='WAITING']]]  
----

If an smtp email server is configured you should received a proper Alert [resolved] email.

== Step IV: Start a log agent

In a new bash session:
 +
[source,shell,subs="+attributes"]
----    
    ./05_agent-log.sh
----

=== Step IV.a: Deploy/Undeploy demo app

In a new bash session:
 +
[source,shell,subs="+attributes"]
----    
    ./06_deploy-app.sh
    ./07_undeploy-app.sh
----

Check that Hawkular Alerting trigger events for deployed and undeployed applications.

[source,shell,subs="+attributes"]
----    
21:33:21,441 INFO  [org.hawkular.alerts.actions.api] (standalone-action-4) HAWKALERT240001: Plugin [email] has received an action message: [StandaloneActionMessage[action=Action[eventId='wildfly-deployments-1478550801091-4c88ec46-69fa-4a48-b36f-f77d5a5d5534', ctime=1478550801091, event=Event [tenantId=my-organization, id=wildfly-deployments-1478550801091-4c88ec46-69fa-4a48-b36f-f77d5a5d5534, ctime=1478550801091, category=TRIGGER, dataId=wildfly-deployments, dataSource=_none_, text=Generate events on deployments, context={}, tags={}, trigger=Trigger [tenantId=my-organization, id=wildfly-deployments, type=STANDARD, eventType=EVENT, name=Deployments on Wildfly Server, description=Generate events on deployments, eventCategory=null, eventText=null, severity=MEDIUM, context={}, actions=[TriggerAction[tenantId='my-organization', actionPlugin='email', actionId='notify-to-developers', states=[], calendar='null']], autoDisable=false, autoEnable=false, autoResolve=false, autoResolveAlerts=true, autoResolveMatch=ALL, memberOf=null, dataIdMap={}, enabled=true, firingMatch=ALL, mode=FIRING, tags={}]], result='WAITING']]]
----

[source,shell,subs="+attributes"]
----
21:32:51,448 INFO  [org.hawkular.alerts.actions.api] (standalone-action-3) HAWKALERT240001: Plugin [email] has received an action message: [StandaloneActionMessage[action=Action[eventId='wildfly-undeployments-1478550771090-54c62ab9-16dc-4999-99cf-806e343158a2', ctime=1478550771090, event=Event [tenantId=my-organization, id=wildfly-undeployments-1478550771090-54c62ab9-16dc-4999-99cf-806e343158a2, ctime=1478550771090, category=TRIGGER, dataId=wildfly-undeployments, dataSource=_none_, text=Generate events on undeployments, context={}, tags={}, trigger=Trigger [tenantId=my-organization, id=wildfly-undeployments, type=STANDARD, eventType=EVENT, name=Undeployments on Wildfly Server, description=Generate events on undeployments, eventCategory=null, eventText=null, severity=MEDIUM, context={}, actions=[TriggerAction[tenantId='my-organization', actionPlugin='email', actionId='notify-to-developers', states=[], calendar='null']], autoDisable=false, autoEnable=false, autoResolve=false, autoResolveAlerts=true, autoResolveMatch=ALL, memberOf=null, dataIdMap={}, enabled=true, firingMatch=ALL, mode=FIRING, tags={}]], result='WAITING']]]
----

If an smtp email server is configured you should received a proper Event email.


=== Step IV.b: Interact with the demo app

Open a browser on:

[source,shell,subs="+attributes"]
----    
	http://localhost:8230/wildfly-helloworld-html5/
----

Introduce _name1_ as a name to generate an app WARN log or _name2_ to generate an app ERROR log.
